Preprocessing

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
predict_conversion_df = pd.read_csv('predict_conversion_in_digital_marketing.csv')

google_ads_df = pd.read_csv('GoogleAds_DataAnalytics_Sales_Uncleaned.csv')

marketing_and_product_df = pd.read_csv('marketing_and_product_performance.csv')

In [36]:
print('The info of Predict Conversion DF:', predict_conversion_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           8000 non-null   int64
 1   Age                  8000 non-null   int64
 2   Gender               8000 non-null   object
 3   Income               8000 non-null   int64
 4   CampaignChannel      8000 non-null   object
 5   CampaignType         8000 non-null   object
 6   AdSpend              8000 non-null   float64
 7   ClickThroughRate     8000 non-null   float64
 8   ConversionRate       8000 non-null   float64
 9   WebsiteVisits        8000 non-null   int64
 10  PagesPerVisit        8000 non-null   float64
 11  TimeOnSite           8000 non-null   float64
 12  SocialShares         8000 non-null   int64
 13  EmailOpens           8000 non-null   int64
 14  EmailClicks          8000 non-null   int64
 15  PreviousPurchases    8000 non-null   int64
 16  LoyaltyPoints        8000 non-null   int64
 17  AdvertisingPlatform  8000 non-null   object
 18  AdvertisingTool      8000 non-null   object
 19  Conversion           8000 non-null   int64
dtypes: float64(5), int64(10), object(5)
memory usage: 1.2+ MB
The info of Predict Conversion DF: None

In [37]:
print('The info of Google Ads DF:', google_ads_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ad_ID            2600 non-null   object
 1   Campaign_Name    2600 non-null   object
 2   Clicks           2488 non-null   float64
 3   Impressions      2546 non-null   float64
 4   Cost             2503 non-null   object
 5   Leads            2552 non-null   float64
 6   Conversions      2526 non-null   float64
 7   Conversion Rate  1974 non-null   float64
 8   Sale_Amount      2461 non-null   object
 9   Ad_Date          2600 non-null   object
 10  Location         2600 non-null   object
 11  Device           2600 non-null   object
 12  Keyword          2600 non-null   object
dtypes: float64(5), object(8)
memory usage: 264.2+ KB
The info of Google Ads DF: None

In [38]:
print('The info of Marketing and Product DF:', marketing_and_product_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Campaign_ID                        10000 non-null  object
 1   Product_ID                         10000 non-null  object
 2   Budget                             10000 non-null  float64
 3   Clicks                             10000 non-null  int64
 4   Conversions                        10000 non-null  int64
 5   Revenue_Generated                  10000 non-null  float64
 6   ROI                                10000 non-null  float64
 7   Customer_ID                        10000 non-null  object
 8   Subscription_Tier                  10000 non-null  object
 9   Subscription_Length                10000 non-null  int64
 10  Flash_Sale_ID                      10000 non-null  object
 11  Discount_Level                     10000 non-null  int64
 12  Units_Sold                         10000 non-null  int64
 13  Bundle_ID                          10000 non-null  object
 14  Bundle_Price                       10000 non-null  float64
 15  Customer_Satisfaction_Post_Refund  10000 non-null  int64
 16  Common_Keywords                    10000 non-null  object
dtypes: float64(4), int64(6), object(7)
memory usage: 1.3+ MB
The info of Marketing and Product DF: None

Mean Imputation for Null Values of Columns in Google Ads DF

In [39]:
# Check for null values in each column
print("\nNull values count per column:")
print(google_ads_df.isnull().sum())

Null values count per column:
Ad_ID                0
Campaign_Name        0
Clicks             112
Impressions         54
Cost                97
Leads               48
Conversions         74
Conversion Rate    626
Sale_Amount        139
Ad_Date              0
Location             0
Device               0
Keyword              0
dtype: int64

In [40]:
# Remove '$' and ',' and convert Cost and Sale_Amount to integers
cols_to_fix = ['Cost', 'Sale_Amount']
for col in cols_to_fix:
    if google_ads_df[col].dtype == 'object' or google_ads_df[col].dtype.name == 'string':
        google_ads_df[col] = google_ads_df[col].astype(str).str.replace(r'[$,]', '', regex=True)
    
    # Convert to numeric, coercing errors to NaN
    # We add .round() to handle decimal values (like cents) safely before casting to Int64
    google_ads_df[col] = pd.to_numeric(google_ads_df[col], errors='coerce').round().astype('Int64')

google_ads_df[cols_to_fix].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Cost         2503 non-null   Int64
 1   Sale_Amount  2461 non-null   Int64
dtypes: Int64(2)
memory usage: 45.8 KB

C:\Users\santo\AppData\Local\Temp\ipykernel_19152\1240373888.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  google_ads_df[col] = google_ads_df[col].astype(str).str.replace(r'[$,]', '', regex=True)
C:\Users\santo\AppData\Local\Temp\ipykernel_19152\1240373888.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  google_ads_df[col] = pd.to_numeric(google_ads_df[col], errors='coerce').round().astype('Int64')
C:\Users\santo\AppData\Local\Temp\ipykernel_19152\1240373888.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  google_ads_df[col] = google_ads_df[col].astype(str).str.replace(r'[$,]', '', regex=True)
C:\Users\santo\AppData\Local\Temp\ipykernel_19152\1240373888.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  google_ads_df[col] = pd.to_numeric(google_ads_df[col], errors='coerce').round().astype('Int64')

In [41]:
# Convert Ad_Date to datetime
google_ads_df['Ad_Date'] = pd.to_datetime(google_ads_df['Ad_Date'], errors='coerce')
google_ads_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ad_ID            2600 non-null   object
 1   Campaign_Name    2600 non-null   object
 2   Clicks           2488 non-null   float64
 3   Impressions      2546 non-null   float64
 4   Cost             2503 non-null   Int64
 5   Leads            2552 non-null   float64
 6   Conversions      2526 non-null   float64
 7   Conversion Rate  1974 non-null   float64
 8   Sale_Amount      2461 non-null   Int64
 9   Ad_Date          893 non-null    datetime64[ns]
 10  Location         2600 non-null   object
 11  Device           2600 non-null   object
 12  Keyword          2600 non-null   object
dtypes: Int64(2), datetime64[ns](1), float64(5), object(5)
memory usage: 269.3+ KB

C:\Users\santo\AppData\Local\Temp\ipykernel_19152\1946985171.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  google_ads_df['Ad_Date'] = pd.to_datetime(google_ads_df['Ad_Date'], errors='coerce')

In [44]:
numeric_cols = google_ads_df.select_dtypes(include=['number']).columns

# We add .round() because 'Int64' columns cannot accept fractional means (e.g., 215.9)
google_ads_df[numeric_cols] = google_ads_df[numeric_cols].fillna(google_ads_df[numeric_cols].mean().round())

# Check for null values again to verify
print("Null values count per column after imputation:")
print(google_ads_df.isnull().sum())

Null values count per column after imputation:
Ad_ID                 0
Campaign_Name         0
Clicks                0
Impressions           0
Cost                  0
Leads                 0
Conversions           0
Conversion Rate       0
Sale_Amount           0
Ad_Date            1707
Location              0
Device                0
Keyword               0
dtype: int64

c:\Users\santo\OneDrive\Documents\GitHub\Learning\.venv\Lib\site-packages\pandas\core\generic.py:7406: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  result[k] = res_k
C:\Users\santo\AppData\Local\Temp\ipykernel_19152\2204650922.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  google_ads_df[numeric_cols] = google_ads_df[numeric_cols].fillna(google_ads_df[numeric_cols].mean().round())

Checking Datasets for Duplicates

In [43]:
# Check number of duplicates in predict_conversion_df
print(f"Number of duplicate rows: {predict_conversion_df.duplicated().sum()}")

# To see the actual duplicate rows (if any)
if predict_conversion_df.duplicated().sum() > 0:
    print("\nDuplicate Rows:")
    print(predict_conversion_df[predict_conversion_df.duplicated()])

Number of duplicate rows: 0

In [45]:
print(f"Number of duplicate rows in Google Ads DF: {google_ads_df.duplicated().sum()}")

if google_ads_df.duplicated().sum() > 0:
    print("\nDuplicate Rows in Google Ads DF:")
    print(google_ads_df[google_ads_df.duplicated()])

Number of duplicate rows in Google Ads DF: 0

In [46]:
print(f"Number of duplicate rows in Marketing and Product DF: {marketing_and_Product_df.duplicated().sum()}")

if marketing_and_Product_df.duplicated().sum() > 0:
    print("\nDuplicate Rows in Marketing and Product DF:")
    print(marketing_and_Product_df[marketing_and_Product_df.duplicated()])

Number of duplicate rows in Marketing and Product DF: 0

One-Hot Encoding

In [47]:
print("Categorical variables in Predict Conversion DF:")
print(predict_conversion_df.select_dtypes(include=['object', 'category']).columns.tolist())

print("\nCategorical variables in Google Ads DF:")
print(google_ads_df.select_dtypes(include=['object', 'category']).columns.tolist())

print("\nCategorical variables in Marketing and Product DF:")
print(marketing_and_product_df.select_dtypes(include=['object', 'category']).columns.tolist())

Categorical variables in Predict Conversion DF:
['Gender', 'CampaignChannel', 'CampaignType', 'AdvertisingPlatform', 'AdvertisingTool']

Categorical variables in Google Ads DF:
['Ad_ID', 'Campaign_Name', 'Location', 'Device', 'Keyword']

Categorical variables in Marketing and Product DF:
['Campaign_ID', 'Product_ID', 'Customer_ID', 'Subscription_Tier', 'Flash_Sale_ID', 'Bundle_ID', 'Common_Keywords']

In [48]:
# One-hot encode categorical variables in predict_conversion_df
categorical_cols = predict_conversion_df.select_dtypes(include=['object', 'category']).columns

# Using drop_first=True to avoid multicollinearity (dummy variable trap)
predict_conversion_df = pd.get_dummies(predict_conversion_df, columns=categorical_cols, drop_first=True, dtype=int)

predict_conversion_df.head()

,CustomerID,Age,Income,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,...,LoyaltyPoints,Conversion,Gender_Male,CampaignChannel_PPC,CampaignChannel_Referral,CampaignChannel_SEO,CampaignChannel_Social Media,CampaignType_Consideration,CampaignType_Conversion,CampaignType_Retention
0,8000,56,136912,6497.870068,0.043919,0.088031,0,2.399017,7.396803,19,...,688,1,0,0,0,0,1,0,0,0
1,8001,69,41760,3898.668606,0.155725,0.182725,42,2.917138,5.352549,5,...,3459,1,1,0,0,0,0,0,0,1
2,8002,46,88456,1546.429596,0.277490,0.076423,2,8.223619,13.794901,0,...,2337,1,0,1,0,0,0,0,0,0
3,8003,32,44085,539.525936,0.137611,0.088004,47,4.540939,14.688363,89,...,2463,1,0,1,0,0,0,0,1,0
4,8004,60,83964,1678.043573,0.252851,0.109940,0,2.046847,13.993370,6,...,4345,1,0,1,0,0,0,0,1,0

In [49]:
google_ads_categorical_cols = google_ads_df.select_dtypes(include=['object', 'category']).columns

google_ads_df = pd.get_dummies(google_ads_df, columns=google_ads_categorical_cols, drop_first=True, dtype=int)

google_ads_df.head()

,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Ad_ID_A1001,Ad_ID_A1002,...,Device_TABLET,Device_Tablet,Device_desktop,Device_mobile,Device_tablet,Keyword_data analitics online,Keyword_data analytics course,Keyword_data anaytics training,Keyword_learn data analytics,Keyword_online data analytic
0,104.0,4498.0,232,14.0,7.0,0.058,1892,2024-11-16,0,0,...,0,0,1,0,0,0,0,0,1,0
1,173.0,5107.0,217,10.0,8.0,0.046,1679,NaT,1,0,...,0,0,0,1,0,0,1,0,0,0
2,90.0,4544.0,204,26.0,9.0,0.000,1624,NaT,0,1,...,0,0,0,0,0,1,0,0,0,0
3,142.0,3185.0,238,17.0,6.0,0.000,1225,2024-11-26,0,0,...,0,0,0,0,1,0,0,1,0,0
4,156.0,3361.0,196,30.0,8.0,0.000,1091,2024-11-22,0,0,...,0,0,1,0,0,0,0,0,0,1

In [50]:
# One-hot encode categorical variables in marketing_and_product_df
marketing_categorical_cols = marketing_and_product_df.select_dtypes(include=['object', 'category']).columns

# Using drop_first=True
marketing_and_product_df = pd.get_dummies(marketing_and_product_df, columns=marketing_categorical_cols, drop_first=True, dtype=int)

marketing_and_product_df.head()

,Budget,Clicks,Conversions,Revenue_Generated,ROI,Subscription_Length,Discount_Level,Units_Sold,Bundle_Price,Customer_Satisfaction_Post_Refund,...,Bundle_ID_BNDL_ZZHJ0V,Bundle_ID_BNDL_ZZL4GJ,Bundle_ID_BNDL_ZZN9RX,Bundle_ID_BNDL_ZZOB89,Bundle_ID_BNDL_ZZWGC1,Bundle_ID_BNDL_ZZXSRS,Bundle_ID_BNDL_ZZYTXF,Common_Keywords_Durable,Common_Keywords_Innovative,Common_Keywords_Stylish
0,41770.45,4946,73,15520.09,1.94,4,43,34,433.80,4,...,0,0,0,0,0,0,0,0,0,0
1,29900.93,570,510,30866.17,0.76,4,28,97,289.29,2,...,0,0,0,0,0,0,0,0,1,0
2,22367.45,3546,265,32585.62,1.41,9,51,160,462.87,4,...,0,0,0,0,0,0,0,0,0,0
3,29957.54,2573,781,95740.12,3.32,32,36,159,334.16,1,...,0,0,0,0,0,0,0,1,0,0
4,36277.19,818,79,81990.43,3.53,29,20,52,371.67,2,...,0,0,0,0,0,0,0,0,0,0